### ISSUE TITLE
I'm having this error and its nothing wrong with the soldering

### ISSUE THREAD

**Issue by GabrielRosa3252** [Levi--G/IMU-WhoAmIVerifier#1]
![image](https://user-images.githubusercontent.com/82677964/157789741-7cec5a64-cf41-4eb4-b77e-56e645cfb6c4.png)
 this is the error

[ERR] Found unknown I2C device on address 0x68 with possible id's:
Reg: 0x75 Value:0x72
Reg: 0x00 Value:0xFD

**Comment by Levi--G** [comment]
Which chip are you trying to detect? do you have a picture of the pcb?

**Comment by Levi--G** [comment]
It seems there are no official invensense chips with id of 0x72 in the mpu line, that would mean this is either a factory sample or a counterfeit, you can try changing the expected id value of the library you use to 0x72 to try and make it work but there is no guarantee it actually will perform as good or even work. mpu 6050 are long out of production and it would surprise me if you can still find official ones.

**Comment by GabrielRosa3252** [comment]
![image](https://user-images.githubusercontent.com/82677964/157915114-acc85361-65f3-4b4a-ae7d-c91a8a4b23a9.png)


Its mpu6050
I can't take picture of the chip but I've checked all the imus and all of them is mpu6050
I've buyed 4 imus but only one worked and the rest are returning this message

You said I can change the id but how can I do this?
