### ISSUE TITLE
MPU9250 errors

### ISSUE THREAD

**Issue by KD9FNA** [Levi--G/IMU-WhoAmIVerifier#5]
I suspect I got a fake chip.  Below are the outputs of the verifier:

```
[ERR] Found unknown I2C device on address 0x68 with possible id's:
Reg: 0x75 Value:0x75
Reg: 0x00 Value:0xC7
```

Breakouts were purchased from Amazon here:
[https://www.amazon.com/dp/B08YNV4JHX?psc=1&ref=ppx_yo2ov_dt_b_product_details](url)

I have a few more I'm going to test, but I'm calling this first one DOA.

**Comment by Levi--G** [comment]
Yes there are a lot of fake/relabeled MPU9250 in circulation, i would avoid them, but they also might just work, they are definitely no official chips though...

**Comment by Levi--G** [comment]
Closing as answered
