### ISSUE TITLE
[ERR] Found unknown I2C device on address 0x28 with possible id's: Reg: 0x75 Value:0x00 Reg: 0x00 Value:0x00...

### ISSUE THREAD

**Issue by uwidev** [Levi--G/IMU-WhoAmIVerifier#6]
[ERR] Found unknown I2C device on address 0x68 with possible id's:
Reg: 0x75 Value:0x00
Reg: 0x00 Value:0x00
Please report this on https://github.com/Levi--G/IMU-WhoAmIVerifier/issues with information above. :)
[ERR] Found unknown I2C device on address 0x69 with possible id's:
Reg: 0x75 Value:0x00
Reg: 0x00 Value:0x00
Please report this on https://github.com/Levi--G/IMU-WhoAmIVerifier/issues with information above. :)
[ERR] Found unknown I2C device on address 0x29 with possible id's:
Reg: 0x75 Value:0x00
Reg: 0x00 Value:0x00
Please report this on https://github.com/Levi--G/IMU-WhoAmIVerifier/issues with information above. :)
[ERR] Found unknown I2C device on address 0x28 with possible id's:
Reg: 0x75 Value:0x00
Reg: 0x00 Value:0x00
Please report this on https://github.com/Levi--G/IMU-WhoAmIVerifier/issues with information above. :)

![20220723_124126](https://user-images.githubusercontent.com/10101319/180620574-845e87cf-6b0b-48a1-8677-9660fc900efd.jpg)
![20220723_124133](https://user-images.githubusercontent.com/10101319/180620578-da9c1679-00d2-45f6-91fd-bea9d3a0e7e5.jpg)

MPU-6500s bought from: https://www.aliexpress.com/item/2251832516905563.html?spm=a2g0o.order_list.0.0.21ef1802h6cWvr

Or so they're supposed to be.

**Comment by uwidev** [comment]
Potentially resolved. Seems like a bad solder. Device now appears as 6500.

**Comment by Levi--G** [comment]
Glad you found it! :)
