### ISSUE TITLE
Unknown Device Reg: 0x75 Value: 0x75 or Reg:0x00 Value:0xC5

### ISSUE THREAD

**Issue by Lascoose** [Levi--G/IMU-WhoAmIVerifier#7]
My primary is a confirmed good MPU 6500, but I bought a new batch of secondary that were labeled as 9250's.  They look legit but I'm assuming they're not.  Anyway to make these work or just return them?

![755167eb5bab83c701e11535918faf2c](https://user-images.githubusercontent.com/75282858/185249636-e5c80da8-0ab2-4efa-9c89-055b346ca757.png)

Amazon Link:
https://www.amazon.com/dp/B08YNV4JHX?psc=1&ref=ppx_yo2ov_dt_b_product_details

**Comment by Levi--G** [comment]
You can always try them, but they do not have an official ID, most likely they are either fakes like many others in the other issues or they are different models that got rebranded.
