### ISSUE TITLE
[ERR] Found unknown I2C device on address 0x68 with possible id's:

### ISSUE THREAD

**Issue by astomx** [Levi--G/IMU-WhoAmIVerifier#8]
[ERR] Found unknown I2C device on address 0x68 with possible id's:
Reg: 0x75 Value:0x75
Reg: 0x00 Value:0xBA

**Comment by Levi--G** [comment]
Still need help on this or did you find it?

**Comment by astomx** [comment]
> Still need help on this or did you find it?

Prob my sensors are broken
